name: Deploy

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm ci

      - name: build
        run: pnpm build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4
        with:
          folder: build
